export const restaurants = [
  // Hidden Halal
  {
    id: "charred-herndon",
    name: "Charred",
    city: "Herndon",
    state: "VA",
    category: "hidden-halal",
    cuisine: "American BBQ",
    tags: ["Burgers", "Wood-Fire", "American"],
    description: "Wood-fire halal burgers done right. Charred is Herndon's best-kept secret — a mainstream smokehouse that serves fully halal meat. The smash burgers are legendary.",
    isHalal: true,
    halalNote: "Fully halal certified. All meat is halal.",
    slug: "charred-herndon",
    featured: true,
    spotlight: true,
  },
  {
    id: "silver-diner",
    name: "Silver Diner",
    city: "Multiple Locations",
    state: "VA",
    category: "hidden-halal",
    cuisine: "American Diner",
    tags: ["Breakfast", "Burgers", "Diner", "Family"],
    description: "The classic American diner that most people don't know has a dedicated halal menu section. Silver Diner's halal options are clearly marked — ask your server.",
    isHalal: true,
    halalNote: "Has a dedicated halal menu section. Ask for the halal menu.",
    slug: "silver-diner",
    featured: false,
    spotlight: false,
  },
  {
    id: "khan-korean-grill",
    name: "Khan Korean Grill",
    city: "Fair Oaks",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Korean BBQ",
    tags: ["Korean BBQ", "KBBQ", "Asian", "Grill"],
    description: "Halal Korean BBQ in Fair Oaks — this one stops people in their tracks. Khan is one of the only fully halal KBBQ spots in NOVA and it does not disappoint.",
    isHalal: true,
    halalNote: "Fully halal. One of the only halal Korean BBQ restaurants in NOVA.",
    slug: "khan-korean-grill",
    featured: true,
    spotlight: false,
  },
  {
    id: "halal-hunan-village",
    name: "Halal Hunan Village",
    city: "Chantilly",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Chinese",
    tags: ["Chinese", "Asian", "Stir Fry", "Noodles"],
    description: "Halal Chinese food in Chantilly — authentic Hunan-style cooking with fully halal ingredients. This is the spot for NOVA's Muslim community craving real Chinese food.",
    isHalal: true,
    halalNote: "Fully halal. Name says it all.",
    slug: "halal-hunan-village",
    featured: false,
    spotlight: false,
  },
  {
    id: "bebop-ashburn",
    name: "Bebop Korean-Mexican",
    city: "Ashburn",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Fusion",
    tags: ["Korean", "Mexican", "Fusion", "Tacos", "Bowls"],
    description: "Korean-Mexican fusion done halal in Ashburn. Bebop is creative, fun, and delicious — think bulgogi tacos and kimchi burritos made with halal meat.",
    isHalal: true,
    halalNote: "Halal meat used. Fusion concept with halal ingredients.",
    slug: "bebop-ashburn",
    featured: false,
    spotlight: false,
  },
  {
    id: "kanoon-herndon",
    name: "Kanoon",
    city: "Herndon",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Smokehouse BBQ",
    tags: ["BBQ", "Smokehouse", "American", "Ribs"],
    description: "A halal smokehouse in Herndon that flies under the radar. Kanoon does proper low-and-slow BBQ with halal meat — brisket, ribs, and all the sides.",
    isHalal: true,
    halalNote: "Halal smokehouse BBQ. Fully halal meat.",
    slug: "kanoon-herndon",
    featured: false,
    spotlight: false,
  },
  {
    id: "nazs-halal-food",
    name: "Naz's Halal Food",
    city: "Sterling",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Street Food",
    tags: ["Street Food", "Chicken Rice", "NYC Cart Style", "Late Night"],
    description: "NYC-style halal cart food in Sterling — and they're open until 4AM. If you know, you know. Naz's is the late-night halal fix NOVA has been waiting for.",
    isHalal: true,
    halalNote: "Fully halal. NYC cart style, open until 4AM.",
    slug: "nazs-halal-food",
    featured: true,
    spotlight: false,
  },
  {
    id: "pizza-twist-ashburn",
    name: "Pizza Twist",
    city: "Ashburn",
    state: "VA",
    category: "hidden-halal",
    cuisine: "Indian Pizza",
    tags: ["Pizza", "Indian", "Fusion", "Halal Pizza"],
    description: "Halal Indian-inspired pizza in Ashburn. Pizza Twist takes desi flavors and puts them on pizza — tikka masala base, paneer toppings, and all halal. Surprisingly addictive.",
    isHalal: true,
    halalNote: "Fully halal. Indian-inspired halal pizza concept.",
    slug: "pizza-twist-ashburn",
    featured: false,
    spotlight: false,
  },

  // Delicious Desi
  {
    id: "charcoal-chicken-chantilly",
    name: "Charcoal Chicken",
    city: "Chantilly",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Pakistani",
    tags: ["Pakistani", "Desi", "Grilled", "Charcoal Chicken"],
    description: "The charcoal chicken here is the stuff of NOVA legend. Marinated, grilled over real charcoal, and served with those chutneys — Charcoal Chicken Chantilly is a staple.",
    isHalal: true,
    halalNote: "Fully halal. Pakistani restaurant.",
    slug: "charcoal-chicken-chantilly",
    featured: true,
    spotlight: false,
  },
  {
    id: "charcoal-kabob-house",
    name: "Charcoal Kabob House",
    city: "Herndon",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Pakistani",
    tags: ["Pakistani", "Desi", "Kabob", "Grilled", "Legacy"],
    description: "Over 25 years in Herndon. Charcoal Kabob House is a NOVA institution — the kind of restaurant that parents took you to growing up and you still go back as an adult.",
    isHalal: true,
    halalNote: "Fully halal. Legacy Pakistani restaurant, 25+ years.",
    slug: "charcoal-kabob-house",
    featured: false,
    spotlight: false,
  },
  {
    id: "lakshmi-chowk",
    name: "Lakshmi Chowk",
    city: "Ashburn",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Pakistani Street Food",
    tags: ["Pakistani", "Street Food", "Chaat", "Desi"],
    description: "Pakistani street food culture brought to Ashburn. Lakshmi Chowk nails the chaotic, delicious energy of a real chowk — chaat, karahi, and everything in between.",
    isHalal: true,
    halalNote: "Fully halal. Pakistani street food concept.",
    slug: "lakshmi-chowk",
    featured: false,
    spotlight: false,
  },
  {
    id: "karahi-boys",
    name: "Karahi Boys",
    city: "Sterling",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Pakistani",
    tags: ["Pakistani", "Desi", "Karahi", "Curry"],
    description: "If you're serious about karahi, Karahi Boys in Sterling is your answer. Proper Pakistani cooking — the karahi here is rich, aromatic, and worth the drive.",
    isHalal: true,
    halalNote: "Fully halal. Pakistani restaurant specializing in karahi.",
    slug: "karahi-boys",
    featured: true,
    spotlight: false,
  },
  {
    id: "bawadi-falls-church",
    name: "Bawadi",
    city: "Falls Church",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Middle Eastern / Desi",
    tags: ["Buffet", "Middle Eastern", "Pakistani", "Halal Buffet"],
    description: "The halal buffet experience in NOVA. Bawadi's spread covers everything from Pakistani curries to Middle Eastern mezze — and it's all halal, all day.",
    isHalal: true,
    halalNote: "Fully halal buffet restaurant.",
    slug: "bawadi-falls-church",
    featured: false,
    spotlight: false,
  },
  {
    id: "spice-village-herndon",
    name: "Spice Village",
    city: "Herndon",
    state: "VA",
    category: "delicious-desi",
    cuisine: "Desi Food Hall",
    tags: ["Food Hall", "Pakistani", "Indian", "Desi", "Variety"],
    description: "A desi food hall in Herndon where multiple vendors share a space. Spice Village is the perfect place when your group can't agree on one restaurant — everyone wins.",
    isHalal: true,
    halalNote: "Fully halal food hall concept.",
    slug: "spice-village-herndon",
    featured: false,
    spotlight: false,
  },

  // Mezze Musts
  {
    id: "sheesh-grill-chantilly",
    name: "Sheesh Grill",
    city: "Chantilly",
    state: "VA",
    category: "mezze-musts",
    cuisine: "Mediterranean / Middle Eastern",
    tags: ["Shawarma", "Mediterranean", "Grill", "Middle Eastern"],
    description: "Sheesh Grill in Chantilly is the go-to for solid Mediterranean halal food. The shawarma is consistent, the portions are generous, and the price is right.",
    isHalal: true,
    halalNote: "Fully halal. Mediterranean grill.",
    slug: "sheesh-grill-chantilly",
    featured: false,
    spotlight: false,
  },
  {
    id: "sk-shawarma",
    name: "SK Shawarma",
    city: "Sterling / Ashburn",
    state: "VA",
    category: "mezze-musts",
    cuisine: "Lebanese / Shawarma",
    tags: ["Shawarma", "Lebanese", "Mediterranean", "Wraps"],
    description: "SK Shawarma has earned a loyal following in Sterling and Ashburn. The chicken shawarma wrap is the move — perfectly seasoned, packed tight, and never disappoints.",
    isHalal: true,
    halalNote: "Fully halal. Lebanese shawarma specialist.",
    slug: "sk-shawarma",
    featured: true,
    spotlight: false,
  },
  {
    id: "darya-kabob",
    name: "Darya Kabob",
    city: "Sterling",
    state: "VA",
    category: "mezze-musts",
    cuisine: "Afghan",
    tags: ["Afghan", "Kabob", "Central Asian", "Kebab"],
    description: "Afghan kabob done right in Sterling. Darya Kabob is the kind of understated spot that locals swear by — tender kebabs, fragrant rice, and that unmistakable Afghan flavor profile.",
    isHalal: true,
    halalNote: "Fully halal. Afghan restaurant.",
    slug: "darya-kabob",
    featured: false,
    spotlight: false,
  },

  // Soy Selects
  {
    id: "krave-shack",
    name: "Krave Shack",
    city: "Chantilly",
    state: "VA",
    category: "hidden-halal",
    cuisine: "American / Wings",
    tags: ["Wings", "Burgers", "American", "Casual"],
    description: "Krave Shack in Chantilly is the halal comfort food spot NOVA needed. Wings, burgers, loaded fries — all halal, all hitting.",
    isHalal: true,
    halalNote: "Fully halal.",
    slug: "krave-shack",
    featured: false,
    spotlight: false,
  },
];

export const categories = [
  {
    id: "hidden-halal",
    name: "Hidden Halal",
    emoji: "🔍",
    description: "Mainstream spots you didn't know were halal",
    color: "#1B7340",
    slug: "hidden-halal",
  },
  {
    id: "delicious-desi",
    name: "Delicious Desi",
    emoji: "🍗",
    description: "The best Pakistani, Indian & South Asian in NOVA",
    color: "#C5960C",
    slug: "delicious-desi",
  },
  {
    id: "mezze-musts",
    name: "Mezze Musts",
    emoji: "🧆",
    description: "Mediterranean, Arab, Turkish & Afghan gems",
    color: "#1B7340",
    slug: "mezze-musts",
  },
  {
    id: "soy-selects",
    name: "Soy Selects",
    emoji: "🥡",
    description: "Halal Asian food done right",
    color: "#C5960C",
    slug: "soy-selects",
  },
  {
    id: "top-tier",
    name: "Top Tier",
    emoji: "⭐",
    description: "The best of the best, regardless of cuisine",
    color: "#C5960C",
    slug: "top-tier",
  },
];

export const cities = [
  "Herndon", "Chantilly", "Sterling", "Ashburn",
  "Fairfax", "Falls Church", "Manassas", "Alexandria", "Fair Oaks"
];
